version: "3.3"

services:
  express:
    image: lualparedes/deel-backend-test:latest
    ports:
      - "3000:3000"

  vite:
    image: lualparedes/deel-frontend-test:latest
    ports:
      - "5173:5173"
    depends_on:
      - express
